### ISSUE TITLE
Support CloudFormation stack tagging when installing Lambda integration

### ISSUE THREAD

**Issue by ericksoen** [newrelic/newrelic-lambda-cli#105]
Our AWS accounts have automation enabled to delete untagged resources, including CloudFormation stacks. The current behavior of the Lambda CLI creates untagged CloudFormation stacks. Unlike the API for Lambda, S3, etc., the AWS CLI does not support tagging CloudFormation resources as an independent operation. You can specify them in an `update-stack` request, but will also need to provide parameter names, etc.

Since using this CLI is the recommended approach from New Relic technical support, it would be a welcome addition to support CloudFormation resource tagging.

## Summary

See above.

## Desired Behaviour

Users can specify tags to associate with their CloudFormation stack.

## Possible Solution

newrelic-lambda integrations install --nr-account-id $nr_account_id --linked-account-name $aws_account_name --nr-api-key ${log_ingestion_api_key} --no-aws-permissions-check --cf-stack-tags Key1=Value1,Key2=Value2,etc.

## Additional context

See above: untagged CloudFormation resources in our AWS accounts are automatically deleted within 24 hours and there's no independent way to add tags to a CloudFormation stack.

**Comment by kolanos** [comment]
Hi @ericksoen, this feature is included in `v0.4.3`. Would welcome any feedback. Thanks.
