### ISSUE TITLE
[layers install] Support installing layer for .NET Core and Java runtime.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/newrelic-lambda-cli#108]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Now New Relic Lambda extension can support .NET Core, Java and Go in addition to node.js and Python.
https://github.com/newrelic/newrelic-lambda-extension/tree/main/examples

It's good to support these runtimes.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour

When the runtime is specified as one of `dotnetcore3.1`, `java8.al2`, `java11`, layers install command will add `NewRelicLambdaExtension` layer.
The layer endpoint returns an available layer.

https://ap-southeast-1.layers.newrelic-external.com/get-layers?CompatibleRuntime=dotnetcore3.1

It seems when code is written in Go, we need another approach since we should use `provided` runtime.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )
How about adding the following key-value pairs to the [RUNTIME_CONFIG](https://github.com/newrelic/newrelic-lambda-cli/blob/v0.2.6/newrelic_lambda_cli/utils.py#L10-L17)

```
    "dotnetcore3.1": {"Handler": "NewRelicExampleDotnet::NewRelicExampleDotnet.Function::FunctionHandler"},
    "java8.al2": {"Handler": "com.newrelic.lambda.example.App::handleRequest"},
    "java11": {"Handler": "com.newrelic.lambda.example.App::handleRequest"},
```

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by kolanos** [comment]
@tanaka-takayoshi lThanks for this suggestion. Couldn't agree more. Will definitely be added in the next CLI release.
