### ISSUE TITLE
[layers install] Add `NEW_RELIC_LAMBDA_EXTENSION_ENABLED=true` environment variable 

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/newrelic-lambda-cli#109]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

New Relic Lambda Layer required `NEW_RELIC_LAMBDA_EXTENSION_ENABLED=true` environment variable.  We have to add this variable manually because `laryers install` command doesn't add it.

https://docs.newrelic.co.jp/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-using-lambda-layer

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

The `layers install` command will add `NEW_RELIC_LAMBDA_EXTENSION_ENABLED=true`.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

How about add env var [here](https://github.com/newrelic/newrelic-lambda-cli/blob/7eb3075186dc2df9246676ea388e8b6542aa40c0/newrelic_lambda_cli/layers.py#L95-L99
)?

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by kolanos** [comment]
@tanaka-takayoshi Thanks for the suggestion. Agree on this one as well, we had to wait for AWS to go public with this feature before we could add this flag. Will be in the next release for sure.
