### ISSUE TITLE
Users must be able to manage custom policies with CloudFormation

### ISSUE THREAD

**Issue by dgillman** [newrelic/newrelic-lambda-cli#118]
The creation of custom policies in a CloudFormation stack means users are unable to use CloudFormation to manage that custom policy themselves.

## Summary

Since the custom policy is created in the [nr-lambda-integration-role.yaml template](https://github.com/newrelic/newrelic-lambda-cli/blob/master/newrelic_lambda_cli/templates/nr-lambda-integration-role.yaml#L56), CloudFormation will not allow creation or maintenance  of that role using CloudFormation created by the user. If a user wants to manage a policy, they likely are in a fairly regimented environment and have elected to exempt themselves from a part of the newrelic-lambda-cli process knowingly. It would be better to provide guidance/requirements for that custom policy and step out of the way. The user has already decided to decline the nicety of having the newrelic-lambda-cli provision it for them.

## Desired Behaviour

- I should be able to manage the custom integration role for lambda integration through my own custom CloudFormation, and should be able to supply the name of the already extant role to the newrelic-lambda-cli

## Possible Solution

- create an additional conditional in the template, which will use a customer-managed, customer-supplied role instead of creating one
- the existing code/template can still be used, if desired, to support users who have availed themselves of the current process

## Additional context

Users who are in a position to create custom policies are likely there because they are subject to heightened security oversight/review and are prohibited from providing the blanket ReadOnly policy which is used by default. My gut feeling is that users with a heightened security review requirement, are also likely required to manage AWS resources through an Infrastructure as Code (IaC) solution such as CloudFormation. This is my situation, anyway, and I doubt I am unique in this.

**Comment by kolanos** [comment]
@dgillman Thanks for reporting The CLI has a `--role-name` argument that allows the user to specify their own role. There's also an `--aws-role-policy` argument. Do these not address  this situation?

**Comment by dgillman** [comment]
@kolanos, thank you for the response. These options do not address the situation.

I cannot claim deep knowledge how the various roles and policies created by `newrelic-lambda` are used. But I have validated my concerns by exercising both options.

`--role-name` supplies a role to the stack created by [./newrelic_lambda_cli/templates/import-template.yaml](https://github.com/newrelic/newrelic-lambda-cli/blob/master/newrelic_lambda_cli/templates/license-key-secret.yaml). It is the role assumed by a "log ingestion" lambda. This is tangential to my issue/concern.

`--aws-role-policy` supplies a policy to the stack created by [./newrelic_lambda_cli/templates/nr-lambda-integration-role.yaml](https://github.com/newrelic/newrelic-lambda-cli/blob/master/newrelic_lambda_cli/templates/nr-lambda-integration-role.yaml). That policy is attached to a role created for overall NewRelic integration. This is the policy I wish to control. I am forced to do so by security policy.

`--aws-role-policy` offers two options:

1. I can omit it, and a universal read policy is granted to NewRelic information. This is not permitted under a "least privileges" security model and will be flatly rejected by my clients' Information Security department. It is a non-starter. I will be creating my own policy.

2. I can supply an `--aws-role-policy`. In this case the argument I supply will be used as a name for a policy which the `newrelic-lambda` CLI creates. But because of the implementation, I will not be able to maintain or manage that policy using CloudFormation. Under the hood `newrelic-lambda` creates a CloudFormation stack. That stack will own the policy. CloudFormation will not allow me to create my own stack to manage the policy.

So, my proposal is that `newrelic-lambda` do less. Or at least I am proposing users have the option to choose to let it do less. I want a way to submit the name of a policy which _I_ control instead of having it created for me. Though this level of automation is thoughtful, the drawback of not being able to use CloudFormation to manage to role is a problem.

**Comment by dgillman** [comment]
Giving this more shape, I would propose the following:

**Comment by kolanos** [comment]
@@dgillman We've released an update that includes this feature. Would be interested in your feedback.
