### ISSUE TITLE
How to specify the version of the lambda?

### ISSUE THREAD

**Issue by C-Kenny** [newrelic/newrelic-lambda-cli#119]
Hi we are wanting to add a version only but not latest. If this possible using the newrelic-lambda tool?

`$ newrelic-lambda layers install -f <lambda-name>`

**Comment by C-Kenny** [comment]
I don't think it's possible. I suspect you have to deploy a new version the more I think about it.

**Comment by kolanos** [comment]
Mutating a function's configuration will result in a function version change.

See: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.update_function_configuration

You could publish a function version  after updating the configuration to treat it as a "snapshot". The above is also available via the AWS CLI as `aws lambda publish-version`.

**Comment by C-Kenny** [comment]
Thanks @kolanos  we were initially going to try the APM layer integration on a trail lambda version but sounds like a new version has to be deployed when a lambda layer is added. Cheers
