### ISSUE TITLE
No option `--disable-license-key-secret` as shown in the setup instructions

### ISSUE THREAD

**Issue by sauln** [newrelic/newrelic-lambda-cli#153]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

When running the command to install the layer into lambda, the instructions list an option that is not supported.

```
newrelic-lambda layers install \
 -f all  \
 --nr-account-id XXXX --disable-extension  --disable-license-key-secret
```

The instructions are the page titled `Setup AWS Lambda monitoring`.  I unfortunately can't link directly to it without exposing my account numbers and such.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

Install `newrelic-lambda-cli==0.5.2` (0.5.3 is not functioning, see #151).
Run the setup commands to setup logging for a lambda.

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

That the instructions would either not have the flag listed, or the flag would work.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Python 3.9, macOS Catalina.

**Comment by kolanos** [comment]
@sauln Thanks for reporting this issue. We will look into resolving this as soon as possible. In the meantime, the `README.md` of this repo should be accurate as a reference.

**Comment by kolanos** [comment]
@sauln This was fixed. Thanks again.
