### ISSUE TITLE
Upgrading the Layer to a newer version results in resetting of all NEW_RELIC_* ENV VARS back to the default

### ISSUE THREAD

**Issue by goldenplec** [newrelic/newrelic-lambda-cli#158]
[NOTE]: When patching to a new version via the CLI for the Lambda layer. That upgrade resets back to the 4 ENV VARS that are set when installing initially.

## Description

[NOTE]: After running a version of the Lambda layer for a period of time. Upgrading to a newer version of the layer using the Lambda CLI

newrelic-lambda subscriptions install --function installed  --aws-region YOUR_REGION

This upgraded my layer but reset all my ENV VARS. As I had configured 

## Steps to Reproduce

[NOTE]: Python Lambda

Set additional NEW_RELIC_ configurations to control other elements of the PYthon agent like logging.

newrelic-lambda subscriptions install --function installed  --aws-region YOUR_REGION

You should now only have 4 ENV VARS left

## Expected Behaviour

[NOTE]: My expectation is that my configuration of my Lambda should be untouched. I configured it how I would like it to run.

## Relevant Logs / Console output

[NOTE]: N/A

## Your Environment

[TIP]: AWS Lambda / Python 3.7 / NR Lambda Layer installed via newrelic-lambda CL

**Comment by kolanos** [comment]
@goldenplec The `newrelic-lambda subscriptions install` command doesn't touch the Lambda function configuration at all. Are you sure it wasn't `newrelic-lambda layers install` (with the `--upgrade` flag)?

**Comment by goldenplec** [comment]
newrelic-lambda layers install \
    --function installed \
    --nr-account-id NR_ACCOUNT_ID \
    --upgrade

Is the upgrade command per

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda

Apologies copied the wrong command

**Comment by kolanos** [comment]
@goldenplec I added a test in #159 and it doesn't appear that `NEW_RELIC_*` environment variables (other than the ones that the CLI maanges) are reset. Are you sure you aren't running `newrelic-lambda layers uninstall` as well?
