### ISSUE TITLE
Unsupported Lambda runtime for {lambdaName}: go1.x

### ISSUE THREAD

**Issue by pgbce** [newrelic/newrelic-lambda-cli#161]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
*Any actual names or references to accountId or others have been swapped for obvious security reasons.

Following steps from [NewRelic official documentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-using-lambda-layer#link-accounts) and receiving an error about unsupported runtime.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
`newrelic-lambda layers install -f lambdaName-staging --nr-account-id {account#}`

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
Integration between Aws and NewRelic was successful. 
Hoping that function gets updated with the newly added layer.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
`✖ Unsupported Lambda runtime for 'lambdaName-staging': go1.x
✨ Install Complete ✨`

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Running this from:
1. cli using iTerm
2. Mac - Catalina

**Comment by pgbce** [comment]
Alright, may have solved this issue by running through [deploy.sh from newrelic-lambda-extension examples](https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/sam/go/deploy.sh).
What it means is that you need to configure your lambda to be deployed with [custom runtimes](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html).

**Comment by kolanos** [comment]
pgbce Thanks for reporting. Yeah, `go1.x` is curiously absent from Lambda's supported runtimes with extensions. We recently added a warning to the CLI to alert `go1.x` users to this. We're not sure when or if `go1.x` will be supported. Our sense is Lambda is moving away from `go1.x`'s RPC implementation in favor of the `provided` approach. But this is mostly speculation at this point.

**Comment by pgbce** [comment]
Thanks @kolanos for providing feedback.
I'm pretty new to the `custom runtime`, is there any specific reasons as to why they may favour the `provided` approach?

**Comment by kolanos** [comment]
@pgbce No, we were surprised by `go1.x`'s absence as well. Should Lambda add extension support for this runtime, we will be sure to publish a layer for it including the extension.
