### ISSUE TITLE
Failed to set up lambda integration: 'service'

### ISSUE THREAD

**Issue by qryuu** [newrelic/newrelic-lambda-cli#17]
Open New Relic One's Modern platforms> Lamda menu
The script downloaded from "Download Setup Script" was executed.

An error message was displayed, but it doesn't matter what caused the error, which is not listed in troubleshooting.

EC2 (Cloud9) is used for the script execution environment, and AdministraotrAccess is assigned to the IAM role.

NR account is used with Admin's authority.

$./newrelic-cloud set-up-lambda-integration --nr-account-id xxxxxx --linked-account-name "xxxxxxx" --nr-api-key aaaaaaaa --regions "ap-northeast-1"
Validating New Relic credentials and retrieving integration license key
Checking for a preexisting link between NR and AWS, and validating the AWS CLI credentials
Creating the AWS role for the New Relic integration
Linking your New Relic account to your AWS account
Cloud integrations account [xxxxxx] already exists in New Relic account [yyyyyy].
Enabling Lambda integration on the link between New Relic and AWS

Failed actions:
  Function: None, Region: None, Error: Failed to set up lambda integration: 'service'

**Comment by qryuu** [comment]
Since it does not support instance profiles,
It is necessary to explicitly set the access key and secret access key in aws configure.

**Comment by qryuu** [comment]
We want you to support instance profile for command execution in EC2.

**Comment by kolanos** [comment]
@qryuu Thanks for reporting this issue. We have just released a new version of the CLI which is boto3 based and does support instance profiles. If you continue to have issues please let us know by creating an issue here. Hope you'll give our new CLI a try and provide any feedback you may have.
