### ISSUE TITLE
InvalidClientTokenId

### ISSUE THREAD

**Issue by justin-seo** [newrelic/newrelic-lambda-cli#18]
On my local machine I am trying to set up linking my AWS account to NR Cloud integrations. But I am running into the following error:

Failed actions:
  Function: None, Region: None, Error: Failed to set up lambda integration:
An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.

I have my AWS credentials set up and set my region but I can't seem to resolve this. Any suggestions?

**Comment by kolanos** [comment]
@justin-seo Thanks for reporting this issue. This was a known issue with the previous implementation, but we have just released a new CLI that is boto3 based and should handle session tokens correctly. If you have any issues with this new CLI please let us know by creating an issue here. Hope you'll give the new CLI a try and provide any feedback.
