### ISSUE TITLE
external_id parser logic wrong

### ISSUE THREAD

**Issue by americanstone** [newrelic/newrelic-lambda-cli#199]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
in the case using integration-arn to overwrite the role.  ```external_id = parse_arn(role_arn)["account"]```
 ` result["resourcetype"], result["resource"] = elements[5].split("/")` throw error 
if role name like 
```arn:aws:iam::xxxxx:role/acct-managed/NewRelicInfrastructure-Integrations```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by kolanos** [comment]
Hi @americanstone, why was the issue closed?

**Comment by americanstone** [comment]
> Hi @americanstone, why was the issue closed?
I use this one to track
https://github.com/newrelic/newrelic-lambda-cli/issues/201

**Comment by americanstone** [comment]
> Hi @americanstone, why was the issue closed?
I use this one to track
https://github.com/newrelic/newrelic-lambda-cli/issues/201
