### ISSUE TITLE
Unsupported runtime error when multiple layers are available

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/newrelic-lambda-cli#206]
## Description

Installing/upgrading all functions leads to unsupported runtime error on functions where multiple layers are available (ARM64 and AMD64).

## Steps to Reproduce

1. A NodeJS12 or NodeJS14 function.
2. `newrelic-lambda layers install --nr-account-id <num> --function all -upgrade --aws-profile default --enable-extension-function-logs`

## Expected Behavior

Functions get the latest layer installed along with necessary env vars and runtime config.

## Relevant Logs / Console output

```
C:\Users\username>newrelic-lambda layers install --nr-account-id <num> --function all -upgrade --aws-profile default --enable-extension-function-logs
✖ Unsupported Lambda runtime for 'arn:aws:lambda:us-west-2:123456789123:function:dev-function1': nodejs14.x
✖ Unsupported Lambda runtime for 'arn:aws:lambda:us-west-2:123456789123:function:dev-function2': nodejs14.x
✖ Unsupported Lambda runtime for 'arn:aws:lambda:us-west-2:123456789123:function:dev-function3': nodejs14.x
Removing New Relic log subscription from 'dev-function4'
✔ Successfully uninstalled log subscription on dev-function4
✔ Successfully installed layer on dev-function4
✖ Install Incomplete. See messages above for details.
```

`dev-function4` is python3.7 runtime which does not have an associated ARM64 layer, so the CLI had no confusion about which layer to install.

## Your Environment

- Windows Terminal
- Python 2.7, Python 3.7, NodeJS 12, NodeJS 14

**Comment by keegoid-nr** [comment]
We should set the default to AMD64 unless specifically choosing ARM64 layers with a flag.

**Comment by kolanos** [comment]
@keegoid-nr The CLI attempts to detect the architecture from the function config.
