### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by mrickard** [newrelic/newrelic-lambda-cli#214]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Python 3.10 is [not yet a Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), but it is a version of Python used by developers on local machines. There's one report of a user unable to run the Lambda CLI on a development machine, so we should prepare to support it as an environment the CLI can run in.

## Desired Behaviour

The CLI should run on a developer's machine with Python 3.10 as the installed Python version. (It currently runs in >= Python 3.6 <= Python 3.9.)

**Comment by mbaranovski** [comment]
#241
