### ISSUE TITLE
Layer causes api gateway to return 502 response

### ISSUE THREAD

**Issue by joeythomaschaske** [newrelic/newrelic-lambda-cli#234]
## Description

I setup the new relic lambda integration, layers, and subscriptions. After installing these my api gateway started returning 502 errors, even though the lambdas were successful. After investigating, apigateway is returning a 502 because of a malformed lambda proxy response.

<img width="1588" alt="Screenshot 2023-04-07 at 5 01 38 PM" src="https://user-images.githubusercontent.com/7061638/230692073-a0b22edc-2b9f-4a52-9621-a37da473b3e3.png">

When I detect drift in my stack it shows the new relic lambda wrapper changes my function handler

<img width="1539" alt="Screenshot 2023-04-07 at 6 39 06 PM" src="https://user-images.githubusercontent.com/7061638/230692507-2bda6697-652d-4129-b8a8-b9837c61c98a.png">

I removed the layers and the api started working again.

## Steps to Reproduce

Create a lambda function that uses [aws-serverless-express](https://www.npmjs.com/package/aws-serverless-express). The response should be returned via express using `response.render`

## Expected Behaviour

The content is returned through api gateway

**Comment by chaudharysaket** [comment]
Resolved in https://github.com/newrelic/newrelic-lambda-layers/issues/141
