### ISSUE TITLE
Unable to find newrelic-log-ingestion lambda due to appended digits

### ISSUE THREAD

**Issue by Jamchello** [newrelic/newrelic-lambda-cli#261]
## Description
The current version of this tool has an issue with the instrumentation of lambda layers. Initially, an outdated version of the log-ingestion lambda was in use. To address this, the outdated NewRelicIngestion stack was removed, and a new one was created using the serverlessrepo. The new stack is labeled as `serverlessrepo-NewRelic-log-ingestion`, and the corresponding deployed lambda function is identified by `newrelic-log-ingestion-129616fa9bcd`. Consequently, the following `stackname` argument is now included during the installation of the integration:

```bash
newrelic-lambda integrations install <NR account ID, API key etc> --stackname serverlessrepo-NewRelic-log-ingestion
```

However, I'm facing an issue where there doesn't seem to be a CLI argument to specify the actual function. This results in the error:

```bash
Creating newrelic-log-ingestion Lambda function in AWS account
✖️ CloudFormation Stack NewRelicLogIngestion exists (status: CREATE_COMPLETE), but newrelic-log-ingestion Lambda function does not.
Please manually delete the stack and re-run this command.
```

Additionally, attempts to resolve this by deleting the stack and running the tool without specifying any stack leads to another error:

```bash
Setting up CloudFormation Stack NewRelicLogIngestion in region: us-east-1
Fetching new CloudFormation template url
✖️ CloudFormation Stack NewRelicLogIngestion exists (status: None).
Please manually delete the stack and re-run this command.
```

## Steps to Reproduce

1. Deploy the NewRelic-log-ingestion application using the serverless repository with the ARN `arn:aws:serverlessrepo:us-east-1:463657938898:applications/NewRelic-log-ingestion`.
2. Try installing the lambda integration and instrumenting a lambda using the layer ARN `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicPython310:7`.

## Expected Behaviour

The process should either create a new log-ingestion function or utilize an existing one within the stack.

## Relevant Logs / Console output

The errors and output described in the initial section indicate issues with stack creation and lambda function recognition.

**Comment by chaudharysaket** [comment]
Hi @Jamchello  The message printed by the CLI suggests that there exists newrelic-log-ingestion lambda associated with the `--stackname serverlessrepo-NewRelic-log-ingestion`. Thus that particular last step which typically installs a new log-ingestion-lambda has failed.
In case you don't provide stackname it will create by default `NewRelicLogIngestion` stack, if that already exists then you will receive following message 
✖️ CloudFormation Stack NewRelicLogIngestion exists (status: None).
Please manually delete the stack and re-run this command.

**Comment by chaudharysaket** [comment]
Hi @Jamchello Could you please provide the logs after it crashes? The above logs only indicate the steps that failed.

**Comment by chaudharysaket** [comment]
Hi @Jamchello, This was expected that the latest version v0.9.0 of CLI will not be able to support the `log-ingestion-lambda` [without suffix] created by older versions of the CLI. The latest changes were made in order to bring parity between the changes in [serverlessrepo repo](https://github.com/newrelic/aws-log-ingestion). In case you want to instrument the older version of log-ingestion-lambda, I would suggest using older version of the CLI in the CI workflow.
