### ISSUE TITLE
AWS credentials possibilities are restricted to small use cases

### ISSUE THREAD

**Issue by gtmtech** [newrelic/newrelic-lambda-cli#42]
## Description

Firstly apologies if the following isnt relevant and I've misinterpreted the code and docs and you do do what I am asking. 

Looking through the code and docs, I believe you specify an aws profile or key/secret key as the primary ways of authenticating your boto3 session with aws. If I've read this correctly, this is far too restrictive and undermines the fundamental good practice of using a default credentials provider and letting a user configure credentials outside your tool according to their needs according to the default chain of 5 (not 2) possible credentials locations (and in boto the default 8 lookup locations) - see links below - which is default aws sdk behaviour and much preferred because it would allow newrelic-lambda-api to run on aws codepipeline, aws codebuild, ecs, ec2 etc. etc. without the need for managing profiles artificially.

In essence our fundamental problem is running newrelic-lambda-api as a codebuild step in a codepipeline so once lambdas are deployed I can use newrelic-lambda-api to attach newrelic integration to them as part of a codepipeline build step

## Steps to Reproduce

See the above - set up your own codepipeline and codebuild, and then in a codebuild step (which is configured to use an IAM role) try and use the tool to use the default IAM credentials passed through the http://169.254.169.254 locallink aws address and autowired up as part of the standard AWS ecosystem. newrelic-lambda-api expects a profile on the box or an accesskey/secretaccesskey but the only options available are using an accesskey/secretaccesskey/sessiontoken extracted from the 169.254.169.254 address, or artificially setting up a profile on the box to do this

## Expected Behaviour

I would expect like all tools to support the default credentials provider in the boto/python aws sdk (like all sdks) which allows the external user the ability to configure which one of 5/8 standard credentials locations to use, and use them to run the tool - so that it can be "autowired up" with the right credentials if running on AWS components such as codepipeline or many many other AWS services. 

## Your Environment

AWS Codepipeline, AWS Codebuild

## Additional context

See https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default

See https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html for boto's 8 lookup paths. 8 is the one I want to work.

**Comment by redian** [comment]
Thats precisely the error i get when running the newrelic-lambda-cli on aws codepipeline:

<img width="1579" alt="Screenshot 2019-12-12 at 11 03 34" src="https://user-images.githubusercontent.com/816941/70707017-16875f80-1ccf-11ea-8bee-b167f75f8f5f.png">

**Comment by kolanos** [comment]
Hi @gtmtech, thanks for ˝reporting this issue. The  `--aws-profile` argument is optional and if not set boto3 should revert to its default configuration behavior. Is CodePipeline using the same meta service mechanism as EC2? What environment variables (if any) have been set in a CodePipeline context?

**Comment by kolanos** [comment]
Believe I found the issue. `--aws-profile` defaults to `default` which appears to prevent the meta service lookup:
https://github.com/newrelic/newrelic-lambda-cli/blob/master/newrelic_lambda_cli/cli/decorators.py#L10

Will test further and submit a fix if this is the cause.
