### ISSUE TITLE
add note to readme that aws cli output must be json

### ISSUE THREAD

**Issue by blue-urban-sky** [newrelic/newrelic-lambda-cli#6]
as title, spent a bit of time digging to find out the cryptic error that the exception causes was due to output being text

**Comment by ardias** [comment]
Hi @blue-urban-sky 
Thank you for reporting. We are aware of the issue. We're preparing a small set of fixes to the script that will include a fix for this specific issue.

**Comment by kolanos** [comment]
@blue-urban-sky Thanks for reporting this issue. We've just released a new version of the CLI which is based on boto3 and no longer has this restriction. If you have any issues with the new CLI please let us know by creating an issue. Closing this issue as it is no longer relevant to the CLI implementation.
