### ISSUE TITLE
Readme should use pip3 for installing CLI

### ISSUE THREAD

**Issue by adjohn** [newrelic/newrelic-lambda-cli#76]

**Comment by kolanos** [comment]
@adjohn This is OS specific. On my system `pip` and `pip3` are the same. `pip3` is only a thing on systems where Python 2.x exists. And Python 2.x has reached end-of-life:
https://pythonclock.org

On OSX, if you run:

```bash
brew install python
```

It will install Python 3.7 by default. You have to do an extra step to also get Python 2.x. That command will also symlink `python` and `pip` to `python3` and `pip3` respectively.

We could add a caveat to the "Requirements" section...?
