### ISSUE TITLE
Cannot use function ARN for installing log subscription

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-lambda-cli#81]
## Description

The documentation for `newrelic-lambda subscriptions install` says that the `--function` flag is "the AWS Lambda function name or ARN." However, passing the ARN always yields an error message.

```
newrelic-lambda subscriptions install --function arn:aws:lambda:us-east-1:{account id}:function:{function name} --no-aws-permissions-check
```

> Error retrieving log subscription filters for 'arn:aws:lambda:us-east-1:{account id}:function:{function name}': An error occurred (InvalidParameterException) when calling the DescribeSubscriptionFilters operation: 1 validation error detected: Value '/aws/lambda/arn:aws:lambda:us-east-1:{account id}:function:{function name} at 'logGroupName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+

(Note: I have redacted our account id and function names from the above messages.)

## Steps to Reproduce

See above.

## Expected Behaviour

It should internally translate the function ARN to the function name when deriving the log group name, as implied by the documentation.

## Relevant Logs / Console output

See above.

## Your Environment

Running inside a docker container using version 0.1.22 of this CLI and version 1.18.16 of the AWS CLI.

**Comment by kolanos** [comment]
@rittneje Thanks for reporting this issue. This error is coming from AWS, and the error `regular expression pattern: [.-_/#A-Za-z0-9]+` doesn't appear to allow `:` which would exclude ARNs. Does it work when you just provide the function name?

**Comment by rittneje** [comment]
Correct, it works when I just provide the function name. However, the error is actually because this CLI doesn't handle ARNs, despite what the documentation says. If you look at the error message, it indicates that this code is trying to use '/aws/lambda/{function arn}' as a log group name when interacting with the AWS CLI. This means that it is blindly assuming that the `--function` argument is the name (since the log group name is really supposed to be '/aws/lambda/{function name}').
